### ISSUE TITLE
Move close button to menu bar

### ISSUE THREAD

**Issue by willpatera** [pupil-labs/pyglui#25]
Migrated from pull request: https://github.com/pupil-labs/pupil/pull/233

For the next milestone consider making the close button as a simple X as part of the plugin title bar would be nice (see sketch with 2 ideas below).

![pyglui_close_menu-01](https://cloud.githubusercontent.com/assets/1407224/10752551/06b19fe6-7cbd-11e5-8702-fae2a151d9cc.png)

Top - add close button and keep collapse button. 
Option 2 - add close button and remove collapse button. Clicking/touching the title of plugin minimizes/collapses the plugin menu.

**Comment by mkassner** [comment]
Do we want to go there? I think its going to look/feel a loot like  Windows
in an OS. I d rather have a normal button for closing. Some menus for
example are not closable. Others are part of the sidebar.

**Comment by MichaelBarz** [comment]
`X` is indeed typical for Windows, but it is also common for `delete` actions or other WIMP UIs such as Unity for Linux. Adding this would also increase the *external consistency* of pyglui.
In addition, closing a plugin should be a fast accessible function. This would avoid frustration when a user opened the wrong plugin, because he can just click at the `X` or at the red circle (Mac style) to close it. Especially because the Plugins have only its header visible on startup, but not the close button.

**Comment by willpatera** [comment]
@mkassner -- You're right, this proposal would require a significant amount of internal changes to the codebase, due to the fact that menus can be part of other menus (or menus within menus with menus --- menu-inception) or menus can function as sidebars. 

While this is certainly not one of the most critical issues/enhancements on the todo list - it is something we should discuss for the next milestone (or milestone after next).

**Comment by cpicanco** [comment]
For curiosity, where is the todo list??

**Comment by willpatera** [comment]
I will close this issue because (for now) moving close buttons to the top of plugin lists seems to have solved the problem. @cpicanco - the "todo" list would just be a milestone that is created in the issue tracker. We do not yet have any milestones setup for pyglui.
